#!/usr/bin/python3


def raise_exception():
    a = 2
    b = "2"
    result = a + b
